### ISSUE TITLE
Customizer background transparent

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#231]
Customizer overrides landing page background with transparent background.

![](http://content.screencast.com/users/adbox/folders/Jing/media/321c701b-d1d0-4f07-b666-d9e8a04c4b3a/2015-09-07_1608.png)

**Comment by DavidWells** [comment]
Fixed in CTA shared

**Comment by atwellpub** [comment]
Still having some issues with this one:
http://screencast.com/t/G2x2llxbzS

**Comment by DavidWells** [comment]
word. I will fix that
